### ISSUE TITLE
Question about JEOL config file

### ISSUE THREAD

**Issue by liangyue1133** [nysbc/leginon#1]
Hello, thanks for developing and sharing this nice software. We are using Leginon on JEOL CryoARM 300kV (JEM-3300) and we encountered a problem when doing autofocus because getting and setting operations from TEM have incorrect results. We found that this happened because some of the parameters in jeol.cfg are not correct. This file does not match our JEOL version. Do you have a configuration file for JEOL CryoARM 300kV? And is there a documentation file for the jeol.cfg explaining what those parameters mean? Thank you!

Liangyue

**Comment by anchi2c** [comment]
Hi, Liangyue,

Thanks for the nice comment and the question.  Since we have not had an installation on CryoARM 300kV, I can not give you an example jeol.cfg.  I am happy to work with you in the modifications we need to make to get it working, though.  As far as explaination of the parameters, have you read https://emg.nysbc.org/redmine/projects/leginon/wiki/Setup_and_Calibration_for_jeolcfg ?  If there are things that is not clear or obvious there, please let me know here or better yet, use the forum https://emg.nysbc.org/redmine/projects/leginon/boards/6.  I can modify that and other documentation there further for the benefit of those to come.

**Comment by liangyue1133** [comment]
Thanks for the reply! We have went through the wiki above and there are still some things left to figure out. Basically we would like to ask the following questions:
1) As for LS1/LS2/LS3/LS4/LM1 magnification boundaries, what is the criterion for choosing of these boundaries? We saw in the wiki that these boundaries can be determined according to the presets. Does it mean that it is appropriate to set the boundaries based on our commonly used magnifications?
2) What does the term "click" physically refer to in "convert beam tilt clicks to angle in radians" or "convert shift clicks to distance in meters"?
3) How to acquire the aperture values? How can we know what values are available in a microscope? As in the example below, where do these five values come from? 
CLA_SIZES = 0, 150e-6, 70e-6, 50e-6, 20e-6

By the way, we would like to ask these questions through the forum, but our registered account has not been approved yet. I applied for an account last Friday using the email "guoliangyue313@gmail.com" and now it is still under review.

Liangyue
